
jobs:
  include:

    # - stage: Unit Testing
    #   language: generic
    #   os: linux
    #   env: running unit and widget tests with code coverage
    #   before_script:
    #     - cd $TRAVIS_BUILD_DIR/flutter_lovebank
    #     - sudo apt-get install -y --no-install-recommends lib32stdc++6 libstdc++6 > /dev/null
    #     - git clone https://github.com/flutter/flutter.git -b beta
    #     - export PATH="$PATH":"$HOME/.pub-cache/bin"
    #     - export PATH=`pwd`/flutter/bin:`pwd`/flutter/bin/cache/dart-sdk/bin:$PATH
    #     - flutter precache
    #     - flutter doctor -v
    #     - pub global activate coverage
    #   script: flutter test --coverage
    #   after_success: bash <(curl -s https://codecov.io/bash) -f coverage/lcov.info

    - stage: Fastlane iOS Build
      language: objective-c
      os: osx
      osx_image: xcode12
      podfile: $TRAVIS_BUILD_DIR/flutter_lovebank/ios/Podfile
      cache:
          directories:
            - $HOME/.pub-cache
      before_install:
        - echo -e "machine github.com\n  login $GITHUB_USER\n  password $GITHUB_USER_PASSWORD" > ~/.netrc
      install:
        - cd ..
        - pwd
        - ls
        - git clone https://github.com/flutter/flutter.git -b stable
        - export PATH=`pwd`/flutter/bin:`pwd`/flutter/bin/cache/dart-sdk/bin:$PATH
        - flutter doctor
        - ls
      script:
        - cd $TRAVIS_BUILD_DIR
        - git clone https://github.com/BabyCube/lovebank-cert.git
        - cd lovebank-cert 
        - mv GoogleService-Info.plist $TRAVIS_BUILD_DIR/flutter_lovebank/ios/Runner
        - cd $TRAVIS_BUILD_DIR/flutter_lovebank/ios
        - bundle install
        - flutter clean
        - flutter pub get
        - flutter precache
        - (cd $HOME && ls)
        - (cd $TRAVIS_BUILD_DIR && ls)
        - (cd $HOME/flutter/.pub-cache//hosted/pub.dartlang.org && ls)
        - (cd $TRAVIS_BUILD_DIR/flutter/.pub-cache//hosted/pub.dartlang.org && ls)
        # - flutter build ios --release --no-codesign
        # - pod install # almost all pods will pre-build at this stage 
        - fastlane betatravis

  #   - stage: Fastlane Andriod Build
